import { Rig } from './pty-rig.mjs';
const r = new Rig(100, 32, { JEEVES_ZAI_BASE_URL: 'http://127.0.0.1:4123' });
await r.until((t) => t.includes('Just chat'), 15000);
r.send('\r');
await r.until((t) => t.includes('Settings'), 15000, 'conversation');
await r.wait(800);
r.send('Write about 900 words on the history of Spain, in many short paragraphs.');
await r.wait(300); r.send('\r');
await r.until((t) => t.includes('▎'), 30000, 'answer starts');
await r.wait(2000);
r.raw = '';
console.log('--- resize mid-stream 100x32 -> 120x45');
r.proc.resize(120, 45); r.term.resize(120, 45); r.cols = 120; r.rows = 45;
await r.wait(700);
const chunk = r.raw;
console.log('raw bytes:', chunk.length, '| 2J count:', (chunk.match(/\x1b\[2J/g) ?? []).length);
console.log('screen row 45:', JSON.stringify(r.screen()[44]?.slice(0, 50)));
console.log('screen row 32:', JSON.stringify(r.screen()[31]?.slice(0, 50)));
// audit the whole screen for duplicate bars
const scr = r.screen();
const bars = scr.filter((l) => /Settings/.test(l) && /Session:|Week:|today/.test(l)).length;
console.log('bars:', bars);
r.kill(); await r.wait(500); process.exit(0);
