// The window with no outer border: dividers, separate typing area, info bar; Settings and Picture click.
import { Rig } from './pty-rig.mjs';
import { writeFileSync } from 'node:fs';
writeFileSync('/private/tmp/jv-chosen.png', Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNkYPhfDwAChwGA60e6kgAAAABJRU5ErkJggg==', 'base64'));
const R = 30;
const r = new Rig(100, R, { JEEVES_ZAI_BASE_URL: 'http://127.0.0.1:4123', JEEVES_PICKER_FILE: '/private/tmp/jv-chosen.png' });
await r.bootConversation(); await r.wait(1500);
console.log(r.screen().map((l, i) => String(i + 1).padStart(2) + '|' + l).join('\n'));
console.log('mouse on:', r.mouseOn());
const bar = r.screen().findIndex((l) => /Settings\s+Picture/.test(l)) + 1;
console.log('bar row', bar, 'of', R);
r.mouse('press', 5, bar); r.mouse('release', 5, bar); await r.wait(1500);
console.log('Settings click ->', r.screen()[0]);
r.send('\x1b'); await r.wait(1200);
const bar2 = r.screen().findIndex((l) => /Settings\s+Picture/.test(l)) + 1;
const pc = r.screen()[bar2 - 1].indexOf('Picture') + 2;
r.mouse('press', pc, bar2); r.mouse('release', pc, bar2);
await r.until((t) => t.includes('[Image 1]'), 8000, 'picture added');
console.log('Picture click -> [Image 1]:', r.text().includes('[Image 1]'));
r.kill(); await r.wait(300); process.exit(0);
