const { execSync } = require('child_process');
const assert = require('assert');
const crypto = require('crypto');
const fs = require('fs');
const dir = process.argv[2];
assert.strictEqual(crypto.createHash('sha256').update(fs.readFileSync(dir + '/stock.test.js')).digest('hex'), process.argv[3], 'the test file was changed');
execSync('node --test', { cwd: dir, stdio: 'pipe' });
const { Portfolio } = require(dir + '/stock.js');
let p = new Portfolio();
p.buy(10, 5); p.buy(10, 8);
assert.strictEqual(p.sell(15, 10), 60);
assert.strictEqual(p.sell(5, 7), -5);
assert.strictEqual(p.held(), 0);
assert.throws(() => p.sell(1, 10), undefined, 'selling more than held must be refused');
p = new Portfolio();
p.buy(3, 100); p.split(2);
assert.strictEqual(p.held(), 6);
assert.strictEqual(p.sell(4, 60), 40);
p.buy(2, 55);
assert.strictEqual(p.sell(3, 50), -5);
assert.strictEqual(p.held(), 1);
p = new Portfolio();
p.buy(3, 10.1); p.buy(1, 3.33);
assert.throws(() => p.sell(5, 20), undefined, 'must refuse');
assert.strictEqual(p.held(), 4, 'a refused sale must not change holdings');
assert.strictEqual(p.sell(4, 12.07), 14.65);
p = new Portfolio();
p.buy(7, 1.1); p.split(3); p.split(0.5);
assert.strictEqual(p.held(), 10.5);
assert.strictEqual(p.sell(10.5, 1), 2.8);
console.log('PASS');
