// The only doors between the window and the engine (the window itself has no Node).
const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('jeeves', {
  ready: () => ipcRenderer.invoke('ready'),
  chooseFolder: (folder) => ipcRenderer.invoke('choose-folder', folder ?? null),
  changeFolder: () => ipcRenderer.send('change-folder'),
  cancelChangeFolder: () => ipcRenderer.send('cancel-change-folder'),
  send: (text, images) => ipcRenderer.send('send', text, images),
  answerQuestion: (index) => ipcRenderer.send('answer-question', index),
  answer: (letter) => ipcRenderer.send('answer', letter),
  stop: () => ipcRenderer.send('stop'),
  toggleTasks: () => ipcRenderer.send('toggle-tasks'),
  stopTask: (id) => ipcRenderer.send('stop-task', id),
  copyText: (text) => ipcRenderer.invoke('copy-text', text),
  openExternal: (url) => ipcRenderer.send('open-external', url),
  setAddress: (value) => ipcRenderer.invoke('set-address', value),
  settings: () => ipcRenderer.invoke('settings'),
  rewindPoints: () => ipcRenderer.invoke('rewind-points'),
  rewindTo: (id) => ipcRenderer.invoke('rewind-to', id),
  spending: () => ipcRenderer.invoke('spending'),
  memoryNotes: () => ipcRenderer.invoke('memory-notes'),
  forgetNote: (id) => ipcRenderer.invoke('forget-note', id),
  conversations: () => ipcRenderer.invoke('conversations'),
  resumeConversation: (id) => ipcRenderer.invoke('resume-conversation', id),
  deleteConversation: (id) => ipcRenderer.invoke('delete-conversation', id),
  models: (provider) => ipcRenderer.invoke('models', provider),
  chooseModel: (provider, id) => ipcRenderer.invoke('choose-model', provider, id),
  saveKey: (provider, key) => ipcRenderer.invoke('save-key', provider, key),
  removeKey: (provider) => ipcRenderer.invoke('remove-key', provider),
  signIn: () => ipcRenderer.invoke('openrouter-sign-in'),
  cancelSignIn: () => { ipcRenderer.send('openrouter-sign-in-cancel'); ipcRenderer.send('chatgpt-sign-in-cancel'); },
  chatGptSignIn: () => ipcRenderer.invoke('chatgpt-sign-in'),
  onSignInUrl: (listener) => ipcRenderer.on('sign-in-url', (_event, url) => listener(url)),
  setLimit: (value) => ipcRenderer.invoke('set-limit', value),
  onOpenHelp: (listener) => ipcRenderer.on('open-help', () => listener()),
  onOpenSettings: (listener) => ipcRenderer.on('open-settings', () => listener()),
  onSettingsChanged: (listener) => ipcRenderer.on('settings-changed', () => listener()),
  onState: (listener) => ipcRenderer.on('state', (_event, state) => listener(state)),
  onEngineCrashed: (listener) => ipcRenderer.on('engine-crashed', (_event, info) => listener(info)),
});
